name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: echo Installing zig 
    - run: npm install zig
  
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - run: echo Runnng master test...
    - run: echo Test succesful.
