name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: echo Installing zig
    - uses: actions/checkout@v1
    - uses: npm install zig
  
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: echo Testing 
    - run: ./tests/main.py
